import { Project } from "@/lib/types";

export const projects: Project[] = [
    {
        id: "tarajim-for-kids",
        title: "Tarajim For Kids",
        description: "Bilingual educational web application for teaching children about the lives of the Sahaba",
        category: "Code",
        tags: ["JavaScript", "Education", "Bilingual"],
        repoUrl: "https://github.com/NewPyDev/tarajim-for-kids",
    },
    {
        id: "woodworking-portfolio",
        title: "Woodworking Portfolio",
        description: "Professional woodworking portfolio showcasing CNC, Polyboard, ArtCAM, and Aspire expertise",
        category: "Design",
        tags: ["HTML", "Portfolio", "CNC"],
        repoUrl: "https://github.com/NewPyDev/woodworking-portfolio",
    },
    {
        id: "Maps-Biz-Scraper",
        title: "Maps Biz Scraper",
        description: "A Python tool to efficiently extract and scrape business leads from Google Maps.",
        category: "Code",
        tags: ["Python", "Scraper", "Automation"],
        repoUrl: "https://github.com/NewPyDev/Maps-Biz-Scraper",
    },
    {
        id: "whatsapp-order-management-system",
        title: "WhatsApp Order Management",
        description: "Comprehensive system to manage, track, and process e-commerce orders directly via WhatsApp.",
        category: "Code",
        tags: ["JavaScript", "WhatsApp API", "E-commerce"],
        repoUrl: "https://github.com/NewPyDev/whatsapp-order-management-system",
    },
    {
        id: "youtube-viewer-bot",
        title: "YouTube Viewer Bot",
        description: "Automated Python bot designed to interact with the YouTube API for various automation workflows.",
        category: "Code",
        tags: ["Python", "YouTube API", "Automation"],
        repoUrl: "https://github.com/NewPyDev/youtube-viewer-bot",
    },
    {
        id: "Yu-Gi-Oh-Card-Combination-Rankings",
        title: "Yu-Gi-Oh Card Rankings",
        description: "A web application for ranking and analyzing Yu-Gi-Oh card combinations.",
        category: "Code",
        tags: ["JavaScript", "Game Data", "Web App"],
        repoUrl: "https://github.com/NewPyDev/Yu-Gi-Oh-Card-Combination-Rankings",
        demoUrl: "https://yu-gi-oh-card-combination-rankings.vercel.app",
    },
    {
        id: "modern-bedroom-closet",
        title: "Modern Bedroom Wardrobe & Desk",
        description: "A custom 6-door ceiling-height wardrobe featuring an integrated floating vanity desk built with precision layout in Polyboard.",
        category: "Design",
        tags: ["Polyboard", "Wardrobe", "Interior"],
        imageUrl: "/assets/polyboard1.jpeg",
    },
    {
        id: "contemporary-living-room-unit",
        title: "Contemporary Living Room Built-in",
        description: "A seamless entryway and living room storage unit blending high-gloss cream cabinets with warm wood textures and integrated mirror backing.",
        category: "Design",
        tags: ["Polyboard", "Living Room", "Storage"],
        imageUrl: "/assets/polyboard3.jpeg",
    },
    {
        id: "pharmacy-shop-fitting",
        title: "Pharmacy Retail Shelving",
        description: "Comprehensive pharmacy shop fitting designed for optimal organization, featuring customized sections for specific product types and clean, modern aesthetics.",
        category: "Design",
        tags: ["Polyboard", "Retail", "Commercial"],
        imageUrl: "/assets/polyboard4.jpeg",
    },
    {
        id: "shoe-store-display",
        title: "Premium Shoe Store Display",
        description: "Boutique shoe store display solution with integrated LED strip lighting and elegant material contrast.",
        category: "Design",
        tags: ["Polyboard", "Retail", "Lighting"],
        imageUrl: "/assets/polyboard5.jpeg",
    },
    {
        id: "slatted-wood-divider",
        title: "Decorative Wood Slat Divider",
        description: "An elegant partial room divider utilizing vertical wood slats combined with lower storage cabinets to create subtle spatial separation.",
        category: "Design",
        tags: ["Polyboard", "Divider", "Interior"],
        imageUrl: "/assets/polyboard7.jpeg",
    },
    {
        id: "modern-tv-unit",
        title: "Modern Integrated TV Unit",
        description: "A floor-to-ceiling TV wall unit incorporating extensive display shelving, a designated mounting plate, and smart cable management.",
        category: "Design",
        tags: ["Polyboard", "Living Room", "Entertainment"],
        imageUrl: "/assets/polyboard8.jpeg",
    },
    {
        id: "l-shaped-kitchen",
        title: "Compact L-Shaped Kitchen",
        description: "A space-optimized L-shaped kitchen design showing integrated appliances and an illuminated vertical pantry shelving unit.",
        category: "Design",
        tags: ["Polyboard", "Kitchen", "Cabinetry"],
        imageUrl: "/assets/polyboard9.jpeg",
    },
    {
        id: "medical-reception-desk",
        title: "Medical Diagnostic Reception",
        description: "A sleek, professional curved reception desk tailored for a medical diagnostic center (Al Akça) featuring branded lighting.",
        category: "Design",
        tags: ["Polyboard", "Commercial", "Reception"],
        imageUrl: "/assets/polyboard10.jpeg",
    },
    {
        id: "modern-pharmacy-interior",
        title: "Modern Pharmacy Interior Layout",
        description: "A contemporary pharmacy layout utilizing striking hexagonal wall shelving, distinct service counters, and categorised back-wall storage.",
        category: "Design",
        tags: ["Polyboard", "Commercial", "Interior"],
        imageUrl: "/assets/polyboard11.jpeg",
    }
];
