import { Project, Service, Testimonial } from "@/lib/types";

export const projects: Project[] = [
    {
        id: "tarajim-for-kids",
        title: "Tarajim For Kids",
        description: "Bilingual educational web application for teaching children about the lives of the Sahaba",
        category: "Code",
        tags: ["JavaScript", "Education", "Bilingual"],
        repoUrl: "https://github.com/NewPyDev/tarajim-for-kids",
    },
    {
        id: "woodworking-portfolio",
        title: "Woodworking Portfolio",
        description: "Professional woodworking portfolio showcasing CNC, Polyboard, ArtCAM, and Aspire expertise",
        category: "Code",
        tags: ["HTML", "Portfolio", "CNC"],
        repoUrl: "https://github.com/NewPyDev/woodworking-portfolio",
    },
    {
        id: "Maps-Biz-Scraper",
        title: "Maps Biz Scraper",
        description: "A Python tool to efficiently extract and scrape business leads from Google Maps.",
        category: "Code",
        tags: ["Python", "Scraper", "Automation"],
        repoUrl: "https://github.com/NewPyDev/Maps-Biz-Scraper",
    },
    {
        id: "whatsapp-order-management-system",
        title: "WhatsApp Order Management",
        description: "Comprehensive system to manage, track, and process e-commerce orders directly via WhatsApp.",
        category: "Code",
        tags: ["JavaScript", "WhatsApp API", "E-commerce"],
        repoUrl: "https://github.com/NewPyDev/whatsapp-order-management-system",
    },
    {
        id: "youtube-viewer-bot",
        title: "YouTube Viewer Bot",
        description: "Automated Python bot designed to interact with the YouTube API for various automation workflows.",
        category: "Code",
        tags: ["Python", "YouTube API", "Automation"],
        repoUrl: "https://github.com/NewPyDev/youtube-viewer-bot",
    },
    {
        id: "Yu-Gi-Oh-Card-Combination-Rankings",
        title: "Yu-Gi-Oh Card Rankings",
        description: "A web application for ranking and analyzing Yu-Gi-Oh card combinations.",
        category: "Code",
        tags: ["JavaScript", "Game Data", "Web App"],
        repoUrl: "https://github.com/NewPyDev/Yu-Gi-Oh-Card-Combination-Rankings",
        demoUrl: "https://yu-gi-oh-card-combination-rankings.vercel.app",
    },
    {
        id: "modern-bedroom-closet",
        title: "Modern Bedroom Wardrobe & Desk",
        description: "A custom 6-door ceiling-height wardrobe featuring an integrated floating vanity desk built with precision layout in Polyboard.",
        category: "Design",
        tags: ["Polyboard", "Wardrobe", "Interior"],
        imageUrl: "/assets/polyboard1.jpeg",
    },
    {
        id: "contemporary-living-room-unit",
        title: "Contemporary Living Room Built-in",
        description: "A seamless entryway and living room storage unit blending high-gloss cream cabinets with warm wood textures and integrated mirror backing.",
        category: "Design",
        tags: ["Polyboard", "Living Room", "Storage"],
        imageUrl: "/assets/polyboard3.jpeg",
    },
    {
        id: "pharmacy-shop-fitting",
        title: "Pharmacy Retail Shelving",
        description: "Comprehensive pharmacy shop fitting designed for optimal organization, featuring customized sections for specific product types and clean, modern aesthetics.",
        category: "Design",
        tags: ["Polyboard", "Retail", "Commercial"],
        imageUrl: "/assets/polyboard4.jpeg",
    },
    {
        id: "shoe-store-display",
        title: "Premium Shoe Store Display",
        description: "Boutique shoe store display solution with integrated LED strip lighting and elegant material contrast.",
        category: "Design",
        tags: ["Polyboard", "Retail", "Lighting"],
        imageUrl: "/assets/polyboard5.jpeg",
    },
    {
        id: "slatted-wood-divider",
        title: "Decorative Wood Slat Divider",
        description: "An elegant partial room divider utilizing vertical wood slats combined with lower storage cabinets to create subtle spatial separation.",
        category: "Design",
        tags: ["Polyboard", "Divider", "Interior"],
        imageUrl: "/assets/polyboard7.jpeg",
    },
    {
        id: "modern-tv-unit",
        title: "Modern Integrated TV Unit",
        description: "A floor-to-ceiling TV wall unit incorporating extensive display shelving, a designated mounting plate, and smart cable management.",
        category: "Design",
        tags: ["Polyboard", "Living Room", "Entertainment"],
        imageUrl: "/assets/polyboard8.jpeg",
    },
    {
        id: "l-shaped-kitchen",
        title: "Compact L-Shaped Kitchen",
        description: "A space-optimized L-shaped kitchen design showing integrated appliances and an illuminated vertical pantry shelving unit.",
        category: "Design",
        tags: ["Polyboard", "Kitchen", "Cabinetry"],
        imageUrl: "/assets/polyboard9.jpeg",
    },
    {
        id: "medical-reception-desk",
        title: "Medical Diagnostic Reception",
        description: "A sleek, professional curved reception desk tailored for a medical diagnostic center (Al Akça) featuring branded lighting.",
        category: "Design",
        tags: ["Polyboard", "Commercial", "Reception"],
        imageUrl: "/assets/polyboard10.jpeg",
    },
    {
        id: "modern-pharmacy-interior",
        title: "Modern Pharmacy Interior Layout",
        description: "A contemporary pharmacy layout utilizing striking hexagonal wall shelving, distinct service counters, and categorised back-wall storage.",
        category: "Design",
        tags: ["Polyboard", "Commercial", "Interior"],
        imageUrl: "/assets/polyboard11.jpeg",
    },
    {
        id: "VvirusCode",
        title: "AirMax TV Code Fetcher",
        description: "A fully automated CI/CD pipeline that scrapes the weekly AirMax TV activation code from a WordPress site by bypassing content-gating and anti-bot measures, then delivers it instantly via Telegram — with built-in duplicate detection to avoid repeat notifications.",
        category: "Code",
        tags: ["Python", "Web Scraping", "Telegram Bot", "GitHub Actions", "CI/CD"],
        repoUrl: "https://github.com/NewPyDev/VvirusCode",
    },
];

export const services: Service[] = [
    {
        id: "web-scraping",
        title: "Web Scraping Solutions",
        description: "Extract data from any website — even the ones that fight back. Dynamic sites, anti-bot bypasses, and structured, clean output delivered in your preferred format.",
        icon: "Database",
        price: "From $150",
        features: [
            "Single & multi-site extraction",
            "Anti-bot & CAPTCHA bypass",
            "Scheduled & recurring scrapes",
            "Clean CSV/JSON/Excel output",
        ],
        gradient: "from-emerald-500 to-teal-600",
    },
    {
        id: "telegram-discord-bots",
        title: "Telegram & Discord Bots",
        description: "Custom automated assistants that work 24/7. From community management to order tracking and smart notifications — built fast, built to last.",
        icon: "MessageSquare",
        price: "From $100",
        features: [
            "Custom commands & menus",
            "Database integration",
            "Payment & API integrations",
            "Admin dashboards & analytics",
        ],
        gradient: "from-blue-500 to-indigo-600",
    },
    {
        id: "scraper-bot-combo",
        title: "Scraper + Bot Pipeline",
        description: "The full automation stack: scrape data automatically and deliver it straight to your Telegram or Discord. Zero manual work, zero missed updates.",
        icon: "Zap",
        price: "From $250",
        features: [
            "End-to-end automation",
            "Real-time data delivery",
            "Duplicate detection",
            "CI/CD powered scheduling",
        ],
        gradient: "from-violet-500 to-purple-600",
    },
    {
        id: "furniture-design",
        title: "Furniture & Interior Design",
        description: "Professional Polyboard designs for kitchens, wardrobes, retail fittings, and commercial interiors. Production-ready files with 3D renders and precise cut lists.",
        icon: "Layers",
        price: "From $200",
        features: [
            "3D renders & walkthroughs",
            "Manufacturing-ready cut lists",
            "Material cost breakdowns",
            "CNC-ready output files",
        ],
        gradient: "from-amber-500 to-orange-600",
    },
];

export const testimonials: Testimonial[] = [
    {
        id: "testimonial-1",
        name: "Karim B.",
        role: "E-commerce Owner",
        location: "Morocco",
        quote: "Hami built a Telegram bot that sends me real-time order updates from my Shopify store. The setup was smooth, he explained everything clearly, and the bot hasn't gone down once in 6 months. Seriously reliable work.",
        rating: 5,
        initials: "KB",
    },
    {
        id: "testimonial-2",
        name: "Sarah M.",
        role: "Marketing Agency Lead",
        location: "Dubai",
        quote: "We needed business leads scraped from Google Maps across 12 cities — cleanly formatted and deduplicated. Hami delivered structured data in 48 hours, no back-and-forth needed. Will definitely work with him again.",
        rating: 5,
        initials: "SM",
    },
    {
        id: "testimonial-3",
        name: "Rachid T.",
        role: "Interior Designer",
        location: "Algiers",
        quote: "The Polyboard designs Hami delivered for our pharmacy project were production-ready from day one. Precise measurements, clean layouts, realistic 3D renders, and incredibly fast turnaround. A true professional.",
        rating: 5,
        initials: "RT",
    },
];
